# This file was generated by GoReleaser. DO NOT EDIT.
class Vega < Formula
  desc "vega"
  homepage ""
  version "0.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/srijanone/vega/releases/download/v0.0.0/vega_0.0.0_mac_x86_64.tar.gz"
    sha256 "c16f9caa709c28e3e6ea2ea97b88f494afd297a84f0f86ac52593f7dbb71e594"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/srijanone/vega/releases/download/v0.0.0/vega_0.0.0_linux_x86_64.tar.gz"
      sha256 "7d98c914a06af8f229218117f5b9d89db818bfb1b07dadf056daa5d571a6c601"
    end
  end

  def install
    bin.install "vega"
  end

  test do
    system "#{bin}/vega version"
  end
end
