# This file was generated by GoReleaser. DO NOT EDIT.
class Vega < Formula
  desc "vega"
  homepage ""
  version "1.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/srijanone/vega/releases/download/v1.0.5/vega_darwin_amd64.tar.gz"
    sha256 "bae74f7c13446f197249dedd70da41ff0d9553ab2b1f8d19a70ce8a119eb80c0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/srijanone/vega/releases/download/v1.0.5/vega_linux_amd64.tar.gz"
      sha256 "d61ff089a8542f77efa848bce715c1deb60d92d439e532fb3b6aeabcf3c1d519"
    end
  end
  
  depends_on "git"
  depends_on "windmilleng/tap/tilt"

  def install
    bin.install "vega"
  end

  test do
    system "#{bin}/vega version"
  end
end
